### ISSUE TITLE
Inconsistent Casing in FMP

### ISSUE THREAD

**Issue by alexeisolonari** [Royce551/FRESHMusicPlayer#8]
FRESHMusicPlayer has inconsistent casing throughout the app.

## Sometimes, it's sentence casing
![image](https://user-images.githubusercontent.com/17863082/158719973-904abf5e-fc9a-489b-9f0b-7f2426674068.png)
![image](https://user-images.githubusercontent.com/17863082/158720018-70016f9c-a0eb-46d0-bd13-3cf0885ad2ab.png)

## Other Times, It's Title Casing
![image](https://user-images.githubusercontent.com/17863082/158720208-c439478f-a6a4-4020-823c-5832bdb99b78.png)
![image](https://user-images.githubusercontent.com/17863082/158720218-6ff49b3f-b3bc-4621-be23-966ef0af9c8a.png)
![image](https://user-images.githubusercontent.com/17863082/158720235-76b9a11d-15d9-492d-8026-5c8cd06d3476.png)

I would highly suggest sentence casing due to the fact that it's what Windows (and Android) use, and it's what many apps have tended to transition to these days due to its casual tone and friendliness. You could also choose title casing anyway, which is the default on macOS and GNOME.

**Comment by Royce551** [comment]
Will definitely look at making more things sentence cased. "Discord Rich Presence" and "System Transport Controls" won't be changed because they are proper nouns though :p.

**Comment by Royce551** [comment]
Fixed in Ver. 12
